server:
  port: 0

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://notification-db:3306/notificationdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: true

  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema:
        registry:
          url: http://schema-registry:9091

kafka:
  topics:
    client-service-topic:
      name: client-service-notification-topic
      consumer:
        group-id: client-service-notification-topic-id
    rent-service-topic:
      name: rent-service-notification-topic
      consumer:
        group-id: rent-service-notification-topic-id
    payment-service-topic:
      name: payment-service-notification-topic
      consumer:
        group-id: payment-service-notification-topic-id
    notification-service-topic:
      name: notification-service-audit-topic
      consumer:
        group-id: notification-service-audit-topic-id

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

openapi:
  oAuthFlow:
    tokenUrl: http://keycloak:8080/realms/carsharing/protocol/openid-connect/token
  service:
    name: notification-service
    version: 1.0.0
    description: Notification service for working with notifications
    url: http://localhost:8088

springdoc:
  show-actuator: true
  api-docs:
    path: /notification-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /notification-service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'