server:
  port: 8088                      #set port
  error:
    include-message: always       #add error message for all responses

spring:
  application:
    name: api-gateway-server      #set app name
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Is-Proxy-Request, true     #add for all request new header for identify that request was from api-gateway
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-—Åonfigurations:
          '[/**]':                #for all routes permitted all origins, headers and methods
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      metrics:                    #add metrics
        enabled: true
        actuator:
          verbose:
            enabled: true         #add detailed description for actuator
        discovery:
          locator:
            enabled: true         #enable locator for finding registered services
            lower-case-service-id: true

#props for configuration circuit breaker and time limiter
api-gateway-server:
  timeout-ms: 5000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 75
  permitted-num-of-calls-in-half-open-state: 5
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 10000
  client-service-uri: lb://client-service
  car-service-uri: lb://car-service
  rent-service-uri: lb://rent-service
  audit-service-uri: lb://audit-service
  notification-service-uri: lb://notification-service
  payment-service-uri: lb://payment-service

#config for managing endpoints
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#config for connection to eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka