server:
  port: 0

spring:
  application:
    name: rent-service
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3308/rentdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema:
        registry:
          url: http://schema-registry:9091

kafka:
  topics:
    audit-topic:
      name: rent-service-audit-topic
    notification-topic:
      name: rent-service-notification-topic

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

openapi:
  oAuthFlow:
    tokenUrl: http://localhost:8080/realms/carsharing/protocol/openid-connect/token
  service:
    name: rent-service
    version: 1.0.0
    description: Rent service for working with rents
    url: http://localhost:8088

springdoc:
  show-actuator: true
  api-docs:
    path: /rent-service/v3/api-docs
  swagger-ui:
    path: /rent-service/swagger-ui/index.html

feign:
  client:
    car-service:
      name: car-service
    client-service:
      name: client-service

management:
  endpoints:
    web:
      exposure:
        include: '*'