server:
  port: 0

spring:
  application:
    name: audit-service

  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://audit-db:5432/auditdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema:
        registry:
          url: http://schema-registry:9091

kafka:
  topics:
    client-service-topic:
      name: client-service-audit-topic
      consumer:
        group-id: client-service-audit-topic-id
    car-service-topic:
      name: client-service-audit-topic
      consumer:
        group-id: client-service-audit-topic-id
    rent-service-topic:
      name: rent-service-audit-topic
      consumer:
        group-id: rent-service-audit-topic-id
    payment-service-topic:
      name: payment-service-audit-topic
      consumer:
        group-id: payment-service-audit-topic-id
    notification-service-topic:
      name: notification-service-audit-topic
      consumer:
        group-id: notification-service-audit-topic-id

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

openapi:
  oAuthFlow:
    tokenUrl: http://keycloak:8080/realms/carsharing/protocol/openid-connect/token
  service:
    name: audit-service
    version: 1.0.0
    description: Audit service for working with user's actions
    url: http://localhost:8088

springdoc:
  show-actuator: true
  api-docs:
    path: /audit-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /audit-service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'